language: php
php:
  - '7.1'
cache:
  directories:
    - .composer/cache
before_script: composer install
script:
  - php ./vendor/phpcheckstyle/phpcheckstyle/run.php --src ./DXFighter.php --src ./lib --config ./phpcheckstyle.xml
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests
notifications:
    slack: laecherbar:y1NWyusbhnKv2tGC3XQCmmJW