language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
cache:
  directories:
    - .composer/cache
before_script: composer update
script: php ./vendor/phpcheckstyle/phpcheckstyle/run.php --src ./DXFighter.php --src ./lib --config ./phpcheckstyle.xml
notifications:
    slack: laecherbar:y1NWyusbhnKv2tGC3XQCmmJW